/* Autogenerated file, overwritten by uNmINeD on map generation. */
var UnminedPlayers = [
  {
    "name": "octoTV",
    "x": 573.2996406326923,
    "z": -2256.9559082148457
  },
  {
    "name": "bbemrl",
    "x": -126.30000001192093,
    "z": -158.519943782263
  }
]
